# Numpy

## Installing Packages

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing Libraries

In [2]:
import numpy as np
import time
import sys

## Speed

In [3]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000

start = time.time()
for i in range(len(a)):
    a[i] *= 2
print("\nTime taken for the list:", time.time() - start)


Time taken for the list: 0.022394895553588867


In [4]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000
b = np.array(a)

start = time.time()
b *= 2 # Direct Operation / Vectorization
print("\nTime taken for the list:", time.time() - start)


Time taken for the list: 0.00027179718017578125


## Memory

In [5]:
a = [1, 2, 3, 4, 5]
arr = np.array(a)

print("List size:", sys.getsizeof(a))
print("Array size:", arr.nbytes)

List size: 104
Array size: 40


## Homogenous & Heterogenous

> **_All the datatypes in a heterogenous python list will gets converted to string for a homogenous NumPy Array_**

In [6]:
a = [1, 'a', "apple", 2.1]
print(type(a))
arr = np.array(a)
arr

<class 'list'>


array(['1', 'a', 'apple', '2.1'], dtype='<U32')

## Dimensions and shapes of np arr

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ndim

2

In [8]:
arr.shape # number of rows, number of columns

(2, 3)

## Enteries filling using direct operations / vectorization

In [9]:
arr = np.arange(1, 100, 4) # start, end, step
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [10]:
np.linspace(0, 1, 10) # start, end, no. of divisions

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.logspace(1, 3, 4) # Logarithmic Scale Array
# array starting with 10^1 and ending with 10^3 and array has 3 values only -> start, end, no. of divisions

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [12]:
np.zeros(5) # array full of zeroes

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros([2,3]) # 2 rows, 3 columns full of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones([2, 3, 5, 8], dtype = int)
# ones is also a function like zeroes and yes you can set the datatype, annoying float figures are gone!

array([[[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
        

In [15]:
np.full([5,5], 5) # number of elements, element value

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
np.empty([2, 3]) # Uninitialized Array -> Create an array without setting any values

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.rand(5, 5) # random floats between 0 & 1

array([[0.95114839, 0.99895654, 0.66513402, 0.02740018, 0.33409384],
       [0.71542962, 0.21728458, 0.69067618, 0.87270001, 0.58124102],
       [0.4958509 , 0.20431169, 0.72890856, 0.17062594, 0.94928685],
       [0.80708023, 0.19668996, 0.14943514, 0.87435828, 0.61492782],
       [0.53780953, 0.59449437, 0.67162076, 0.38356937, 0.63361497]])

In [18]:
np.random.randn(5, 5) # random floats between 0 & 1 using standard normal distribution

array([[-0.35950336,  0.55646378, -0.37521204, -0.39445927,  0.0606452 ],
       [-1.42036742, -0.96846766,  1.6787848 , -0.98092467, -1.18351635],
       [ 0.57600943,  0.58553632,  0.19969076,  0.32207672, -0.48095675],
       [ 0.53702465, -0.60742482,  0.54924137, -0.40874145,  3.34632151],
       [ 0.11870795, -0.47000995, -0.79385748,  0.58771911, -0.92872445]])

In [19]:
np.random.randint(1, 10, (5,5)) # random integers

array([[5, 3, 6, 3, 5],
       [2, 6, 5, 5, 2],
       [1, 2, 2, 1, 2],
       [4, 4, 5, 2, 3],
       [8, 2, 7, 3, 8]], dtype=int32)

## Numpy DataTypes & Type Casting

In [20]:
arr = np.array([1, 2, 3.1, 4, 5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [21]:
arr.dtype

dtype('float64')

In [22]:
print(type(arr))

<class 'numpy.ndarray'>


In [23]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [24]:
arr = np.array([1, 2, 31, 4, 5])
arr.dtype

dtype('int64')

In [25]:
arr = np.array([1.1, 2.1, 3, 4], dtype = np.int32)
arr

array([1, 2, 3, 4], dtype=int32)

### Typecasting

In [26]:
# astype()
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [27]:
new_arr = arr.astype(np.float32)
new_arr.dtype

dtype('float32')

In [28]:
arr.dtype # arr remains same, a new array new_arr is created using typecasting

dtype('int64')

#### Type Casting Errors

```
arr = np.array(["1", "2", "Hello"])
arr2 = arr.astype(np.int64)
arr2
```

> *ValueError: invalid literal for int() with base 10: np.str_('Hello')*

## Multidimensional Array

In [29]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr.ndim

2

In [31]:
arr.shape

(2, 3)

In [32]:
arr.size

6

In [33]:
arr.itemsize # bytes

8

## Array Reshaping

### Reshape

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
r_arr = arr.reshape(2, 3)
r_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
r2_arr = r_arr.reshape(3, 2)
r2_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

### Ravel

In [36]:
# convert to 1D Array
rl_arr = r2_arr.ravel()
rl_arr

array([1, 2, 3, 4, 5, 6])

In [37]:
rl_arr[0] = 100 # Shallow copy
print(rl_arr)
print(r2_arr)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


### Flatten

In [38]:
# convert to 1D Array
f_arr = r2_arr.flatten()
f_arr

array([100,   2,   3,   4,   5,   6])

In [39]:
f_arr[0] = 1 # Deep Copy
print(f_arr)
print(r2_arr)

[1 2 3 4 5 6]
[[100   2]
 [  3   4]
 [  5   6]]


## Arithmatic Operations on Arrays

In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [41]:
# Addition
print(a+b)

[5 7 9]


In [42]:
#Subtraction
print(a-b)

[-3 -3 -3]


In [43]:
#Division
print(a/b)

[0.25 0.4  0.5 ]


In [44]:
#Floor Division
print(b//a)

[4 2 2]


In [45]:
#Multiplication
print(a*b)

[ 4 10 18]


In [46]:
#Modulus -> Remainder
print(a%b)

[1 2 3]


In [47]:
#Power
print(a**b)

[  1  32 729]


## Universal Functions ( Ufuncs)

In [48]:
arr = np.array([1, 4, 9, 16])

In [49]:
# Square Root
np.sqrt(arr)

array([1., 2., 3., 4.])

In [50]:
#Exponential -> e^x where x ∈ arr
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [51]:
# sine
angles = np.array([0, np.pi, np.pi/2])
np.sin(angles)

array([0.0000000e+00, 1.2246468e-16, 1.0000000e+00])

## Indexing & Slicing

In [52]:
a = [1,2,3,4,5]

In [53]:
a[-1:-4: -1]

[5, 4, 3]

In [54]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [55]:
# Negative Indexing
print(arr[-1])

50


In [56]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [57]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [58]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


### Index Arrays / Advanced Indexing

In [59]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0, 2] #index = 0, 2
print(np.take(arr, ind))

[10 30]


In [60]:
# Iterating with nditer()
arr= np.array([[1,2], [3,4]])
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [61]:
# ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


### Views

In [62]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [63]:
view[0] = 200 # shallow copy
view

array([200,   3])

In [64]:
arr

array([  1, 200,   3,   4,   5])

### Copy

In [65]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [66]:
copy[0] = 2 # deep copy
copy

array([2, 3])

In [67]:
arr

array([  1, 200,   3,   4,   5])

## Structural Operations on Matrix

### Transpose

In [68]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [69]:
arr.transpose()

array([[1, 3],
       [2, 4]])

### Swap Axes

In [81]:
# Swapaxes -> swap 2 specific axes in a matrix.

arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [82]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

In [72]:
arr

array([[[1, 2],
        [3, 4]]])

### Concatenation

In [83]:
a = np.array([1,2])
b = np.array([3,4])

In [84]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [85]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [86]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [88]:
print(np.stack((arr1, arr2), axis = 0)) # 0 -> row-wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
print(np.stack((arr1, arr2), axis = 1)) # 1 -> column-wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Splitting

In [91]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [93]:
print(np.hsplit(arr1, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


### Repeating

In [94]:
arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


### Tiling

In [96]:
# repeat my whole array

print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


## Aggregate Functions

In [99]:
arr = np.array([1,2,3])
np.sum(arr)

np.int64(6)

In [100]:
np.mean(arr)

np.float64(2.0)

In [101]:
np.median(arr)

np.float64(2.0)

In [102]:
np.std(arr)

np.float64(0.816496580927726)

In [103]:
np.var(arr)

np.float64(0.6666666666666666)

In [104]:
np.max(arr)

np.int64(3)

In [105]:
np.min(arr)

np.int64(1)

In [106]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [108]:
print(np.sum(matrix, axis = 1))

[ 6 15 24]


## Cumulative Functions

In [109]:
print(np.cumsum(arr))

[1 3 6]


In [110]:
print(np.cumprod(arr))

[1 2 6]


## Conditional Based choices

In [112]:
arr

array([1, 2, 3])

In [113]:
result = np.where(arr <2, "low", "high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [114]:
#argwhere: row-column positions for 2d arrays
print(np.argwhere(arr>0)) # returns index where array element's value is more than 0

[[0]
 [1]
 [2]]


In [115]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
print(np.argwhere(matrix> 5)) # 6, 7, 8, 9

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [121]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = np.logical_and(arr > 3, arr < 6)
mask

array([False, False, False,  True,  True, False])

In [122]:
arr[mask]

array([4, 5])

In [123]:
mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True, False, False,  True])

In [124]:
arr[mask]

array([1, 2, 3, 6])

In [127]:
arr2 = np.array([0, 1, 5, 0, 5])
np.nonzero(arr2)

(array([1, 2, 4]),)

## Broadcasting

**Broadcasting Rules:**
1. If shapes are equal, they're compatible
2. If one is 1, it can be stretched to match the other. [1,2,3] + 5 -> [1,2,3] + [5,5,5]
3. If shapes are different and not 1 or equal -> Error

In [128]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [130]:
brightness = image + 50
brightness.shape

(2, 2)

In [131]:
brightness

array([[250, 200],
       [150, 300]])

## Vectorization

In [134]:
def square(x):
  return x*x

vfunc = np.vectorize(square)
vfunc(arr)

array([ 1,  4,  9, 16, 25, 36])

## Dealing With Missing values:

In [136]:
# np.nan -> not a number.
a = np.array([1, 2, np.nan, 4])
a

array([ 1.,  2., nan,  4.])

np.inf and -np.inf -> positive and negative infinites

- np.isnan
- np.isinf
- np.isfinite

These are the functions used to detect any null values, infinte value or fnite value

In [139]:
np.isnan(a)

array([False, False,  True, False])

In [144]:
b = np.array([1, np.nan, -np.inf, 10.2, 40])
print(np.isinf(b))

[False False  True False False]


In [145]:
print(np.isfinite(b))

[ True False False  True  True]


In [146]:
new_b = np.nan_to_num(b) # remove Nan/ infinite values.
new_b

array([ 1.00000000e+000,  0.00000000e+000, -1.79769313e+308,
        1.02000000e+001,  4.00000000e+001])