# Numpy

## Installing Packages

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing Libraries

In [2]:
import numpy as np
import time
import sys

## Speed

In [3]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000

start = time.time()
for i in range(len(a)):
    a[i] *= 2
print("\nTime taken for the list:", time.time() - start)


Time taken for the list: 0.0186307430267334


In [4]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000
b = np.array(a)

start = time.time()
b *= 2 # Direct Operation / Vectorization
print("\nTime taken for the list:", time.time() - start)


Time taken for the list: 0.0002620220184326172


## Memory

In [5]:
a = [1, 2, 3, 4, 5]
arr = np.array(a)

print("List size:", sys.getsizeof(a))
print("Array size:", arr.nbytes)

List size: 104
Array size: 40


## Homogenous & Heterogenous

> **_All the datatypes in a heterogenous python list will gets converted to string for a homogenous NumPy Array_**

In [6]:
a = [1, 'a', "apple", 2.1]
print(type(a))
arr = np.array(a)
arr

<class 'list'>


array(['1', 'a', 'apple', '2.1'], dtype='<U32')

## Dimensions and shapes of np arr

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ndim

2

In [8]:
arr.shape # number of rows, number of columns

(2, 3)

## Enteries filling using direct operations / vectorization

In [9]:
arr = np.arange(1, 100, 4) # start, end, step
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [10]:
np.linspace(0, 1, 10) # start, end, no. of divisions

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.logspace(1, 3, 4) # Logarithmic Scale Array
# array starting with 10^1 and ending with 10^3 and array has 3 values only -> start, end, no. of divisions

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [12]:
np.zeros(5) # array full of zeroes

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros([2,3]) # 2 rows, 3 columns full of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones([2, 3, 5, 8], dtype = int)
# ones is also a function like zeroes and yes you can set the datatype, annoying float figures are gone!

array([[[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
        

In [15]:
np.full([5,5], 5) # number of elements, element value

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
np.empty([2, 3]) # Uninitialized Array -> Create an array without setting any values

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.rand(5, 5) # random floats between 0 & 1

array([[0.19930452, 0.48044532, 0.8977638 , 0.12086703, 0.66735597],
       [0.75865664, 0.50056959, 0.84826333, 0.60679229, 0.13416405],
       [0.64084341, 0.18569634, 0.79408202, 0.05633527, 0.12757547],
       [0.4136525 , 0.83021626, 0.94329294, 0.84107435, 0.64463644],
       [0.58069588, 0.65206085, 0.52000097, 0.88413582, 0.80037415]])

In [18]:
np.random.randn(5, 5) # random floats between 0 & 1 using standard normal distribution

array([[-8.67537571e-02, -2.73666806e-01, -3.27408457e-01,
         8.28787330e-01, -3.18819555e-01],
       [ 7.42642448e-01, -8.57647453e-01, -2.19451326e+00,
        -5.01222896e-01,  1.63362162e+00],
       [-1.51113969e+00, -8.90231260e-01,  1.95526618e-01,
         3.74978899e-01, -7.21870439e-01],
       [-2.59107142e+00,  2.05692187e+00,  2.39392744e-01,
        -8.95411804e-01,  2.56658963e-02],
       [-1.69803880e+00,  2.52470634e-03,  3.17562589e-01,
        -9.79534158e-01,  8.14468007e-01]])

In [19]:
np.random.randint(1, 10, (5,5)) # random integers

array([[6, 2, 4, 9, 7],
       [1, 7, 5, 5, 1],
       [9, 9, 9, 7, 3],
       [3, 4, 9, 1, 5],
       [1, 2, 5, 4, 7]], dtype=int32)